### PR TITLE
Add new frontmatter fields for metaRobots & seoTitle

### PR DESCRIPTION
**Pull request by neo773**
I've got `metaRobots` to work, wanted a clarification on `seoTitle` what do you mean by it? does it have to blog's heading tag?

@devinschumacher 

https://github.com/serpcompany/serp.media/assets/62795688/d9a6c50f-3d10-4e93-a954-22e4733ef1b1

/claim https://github.com/serpcompany/public/issues/5

### CODE REVIEW

**Comment by devinschumacher** [comment]
@neo773 heres the answer to your question about seoTitle - https://www.loom.com/share/8cf250c93a334f59a131b70e5404d2d7

**Comment by neo773** [comment]
@devinschumacher 
Pushed a new commit

https://github.com/serpcompany/serp.media/assets/62795688/4a30bbd9-6f65-41d3-8a7e-cc7c415ad3e8

**Comment by devinschumacher** [comment]
@neo773 thanks looks correct from those videos, however Please review our "[definition of done](https://github.com/serpcompany/public/discussions/8)" for properly submitting this task as "completed".

**Comment by neo773** [comment]
@devinschumacher 

* [x]  Make a 'branch' from the issue to do your work on & submit a PR (don't work on `main`)
* [x]  Complete all items requested in the task (in both the written part of the issue & any accompanying videos (if present)).
> * [ ]  Write `unit tests` & `integration tests` 
About this, I'm not if it's applicable to this PR, as it only extends the `astro-seo` object, they have a pretty extensive e2e test suite for that.
> * [ ]  Film a [loom video]
Do the above posted demo videos qualify for this?
* [x]  Also: the site must build (only applies to repositories that auto-build projects). If you break the build with your submitted work, it will be rejected.

SCR-20240319-fsha

**Comment by neo773** [comment]
I see you've merged another PR, this was a very confusing experience for me as the issue was assigned to me.

image

**Comment by devinschumacher** [comment]
@neo773 software tests not required.
loom video with audio required.
and merge conflict.

**Comment by neo773** [comment]
@devinschumacher 
https://www.loom.com/share/b66e6a97087349bdadae6c726a183736

**Comment by neo773** [comment]
@devinschumacher 
Hi,

I see you've approved the bounty but it hasn't been processed yet.
Could you look into it?

Thanks.

**Comment by devinschumacher** [comment]
@neo773 theres nothing in my algora area that suggests i can do anything about it or any notifications to do something... might need to ask them? im not sure whats up ??

**Comment by neo773** [comment]
@devinschumacher 
You can also do this directly via `/tip $amount` command, I don't think the approve command might work as the bounty was marked as completed in the other merged PR.

**Comment by devinschumacher** [comment]
@neo773 can you send me your contact info? ill just send it to you directly. DM me on instagram @dvnschmchr or linkedin https://linkedin.com/in/devinschumacher

**Comment by neo773** [comment]
@devinschumacher 
Unfortunately I don't have a LinkedIn, you can make the command explicit by typing
`/tip $amount @neo773`
You can find the documentation for all commands here:
https://docs.algora.io/commands

**Pull request closed without merging**
