### PR TITLE
W.I.P: feat: movies collection

### PR DESCRIPTION
**Pull request by mittalyashu**
**Checklist**

- [x]  create a collection for src/content/movies/
- [x]  add in some of the "movies" files below to make sure they work
- [x]  A place in the /sitemap-index.xml for the /movies/ collection
- [x]  The posts will display on a /movies/ slug as a collection,
- [ ]  "Category" tags in the "movies" frontmatter link the "movies" posts together
- [x]  A section on the homepage under the "Posts" area for the "Movies" recent posts

**Notes**

* With the current logic for storing all the blog posts under `post` collection. At some places I have to hard to the `movies` collection value. Let me know, what do you think?
* It would be nice to rename the `post` collection to better fit with the terminology in the codebase. _(it was bit confusion for be initially to understand as well)_

**Loom videos**

_Due to their 5 minute limit on each video on Loom, I have to split into multiple parts._

- [Part 1](https://www.loom.com/share/42367744defe452c8071bd39799ba8c0?sid=6e596915-9d16-4621-a063-804d634ea054)
- [Part 2](https://www.loom.com/share/42367744defe452c8071bd39799ba8c0?sid=6e596915-9d16-4621-a063-804d634ea054)
- [Part 3](https://www.loom.com/share/2e5bc6227f6847bc9924e54c0c6390d3?sid=63688875-7ca0-42e3-ae7e-15b38a14e1c8)
- [Part 4](https://www.loom.com/share/f283e3c836544fe7b509baf8f569c9b7?sid=a363017c-a4d6-438c-81ea-15f28e565a11)
- [Part 5](https://www.loom.com/share/f413fe00abcf42c1a3691ce834ffcde5?sid=6ac5ccae-d87b-4aa5-899a-6ab66c7be672)
- [Part 6](https://www.loom.com/share/a006d90652e94d16a7fd891b58d3dcc8?sid=7e242a60-0e9d-4d74-8587-e4ca833d8b87)

/claim https://github.com/serpcompany/public/issues/6

### CODE REVIEW

**Comment by mittalyashu** [comment]
Please wait on the Loom video, I am still compiling the videos together due to their 5 minute limit on each video.

**Comment by mittalyashu** [comment]
@devinschumacher I didn't quite understood this task,

 - [ ] "Category" tags in the "movies" frontmatter link the "movies" posts together

Can you elaborate it bit more?

**Comment by devinschumacher** [comment]
@mittalyashu 

your questions:

> With the current logic for storing all the blog posts under post collection. At some places I have to hard to the movies collection value. Let me know, what do you think?

^ i dont understand the question can you try to re-phrase it please?

> It would be nice to rename the post collection to better fit with the terminology in the codebase. (it was bit confusion for be initially to understand as well)

^ i agree. it is poorly named and does not match the code!

**Comment by devinschumacher** [comment]
@mittalyashu do you have any recommendations for astro sites that have alot of content in them to keep local dev server ram low? i noticed you did that in loom and it would help me bc sometimes my dev server takes forever to load bc of all the files

**Comment by mittalyashu** [comment]
> do you have any recommendations for astro sites that have alot of content in them to keep local dev server ram low? i noticed you did that in loom and it would help me bc sometimes my dev server takes forever to load bc of all the files

You can use GH codespace, that way you don't have to worry about your laptop (machine) heating up or slowing down.

I did the same.

**Comment by mittalyashu** [comment]
> With the current logic for storing all the blog posts under post collection. At some places I have to hard to the movies collection value. Let me know, what do you think?

_Opps, sorry for the confusion. I have updated the actual notes in the PR description as well. I think loom doesn't have option to copy the video at particular timestamp._

I was referring to this part. Please see this [loom - part 5](https://www.loom.com/share/f413fe00abcf42c1a3691ce834ffcde5?sid=6ac5ccae-d87b-4aa5-899a-6ab66c7be672) at timestamp `01:57`.

You will notice there I have to hardcode the value of the collection.

**Comment by devinschumacher** [comment]
> > With the current logic for storing all the blog posts under post collection. At some places I have to hard to the movies collection value. Let me know, what do you think?
> 
> _Opps, sorry for the confusion. I have updated the actual notes in the PR description as well. I think loom doesn't have option to copy the video at particular timestamp._
> 
> I was referring to this part. Please see this [loom - part 5](https://www.loom.com/share/f413fe00abcf42c1a3691ce834ffcde5?sid=6ac5ccae-d87b-4aa5-899a-6ab66c7be672) at timestamp `01:57`.
> 
> You will notice there I have to hardcode the value of the collection.

It has a work around you can comment and then open the commment and get a link to the comment: https://www.loom.com/share/f413fe00abcf42c1a3691ce834ffcde5?highlightComment=39332084&t=205

**Comment by devinschumacher** [comment]
@mittalyashu

your questions:

> With the current logic for storing all the blog posts under post collection. At some places I have to hard to the movies collection value. Let me know, what do you think?


okay i think i understand what youre saying. 

yes the collection setup on this theme is a bit weird. i spent some time trying to figure it out yesterday and what i found was that to add/reference a collection you need to update like 5 different files. 

i have some rough notes but they are incomplete:

# Adding Collection Notes (WIP):

```md
# WIP...

## Part 1

1. [Create the collection](https://youtu.be/XoIHKO6AkoM?si=aslgAZa0LDP4zPMS&t=3229)
2. [Define the collection schema](https://youtu.be/XoIHKO6AkoM?si=ezGuJwQwKloZNHPo&t=3328)




#### config.yml

1. Create a collection scheme in the `config.yml` file

```.yml
  - name: 'gun-law'
    label: 'Gun Law'
    folder: 'src/content/gun-laws'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
```

#### config.ts

```ts
// src/content/config.ts

// Import necessary modules
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';
import { z, defineCollection } from "astro:content";

// Define a `type` and `schema` for each collection
const postsCollection = defineCollection({
    type: 'content',
    schema: z.object({
      title: z.string(),
      excerpt: z.string().nullable().optional(),
      publishDate: z.union([
        z.date(),
        z.string().refine(value => !isNaN(Date.parse(value)), {
          message: "publishDate must be a valid date string",
        })
      ]).optional(),
      image: z.string().optional(),
      category: z.string().optional(),
      tags: z.array(z.string()).optional(),
      website: z.string().optional(),
      author: z.string().optional(),
      authorImage: z.string().optional(),
      authorTwitterUrl: z.string().optional(),
      authorFacebookUrl: z.string().optional(),
      authorWebsite: z.string().optional(),
    })
});

// Export a single `collections` object to register your collection(s)
export const collections = {
    "gun-laws": postsCollection,
    "hunting-laws": postsCollection,
    "shop": postsCollection,
    "post": postsCollection,
};

// Define the GET function as an async function
export async function GET(context) {
    // Retrieve the collection named 'blog'
    const blog = await getCollection('blog');
  
    // Generate the RSS feed
    return rss({
        title: 'SERP',
        description: 'Learn to Shoot',
        site: context.site,
        items: blog.map((post) => ({
            title: post.data.title,
            author: post.data.author,
            pubDate: post.data.pubDate,
            description: post.data.description,
            customData: post.data.customData,
            content: post.body, // Assuming you have the content of each post in post.body
            link: `/${post.slug}/` // Make sure the link structure matches your routing
        })),
    });
}
```

#### index.astro

```js
    // Fetch all posts from 'shop' collection
    const shopPosts = (await getCollection('shop')) || [];

    // Fetch all posts from 'gun-laws' collection
    const gunLawsPosts = (await getCollection('gun-laws')) || [];

    // Fetch all posts from 'hunting-laws' collection
    const huntingLawsPosts = (await getCollection('hunting-laws')) || [];

    // Combine posts from all collections
    const posts = [...shopPosts, ...gunLawsPosts, ...huntingLawsPosts];
```

#### rss.xml.js


```js
export async function GET(context) {
    // Fetch posts from multiple collections
    const blogPosts = (await getCollection('blog')) || [];
    const gunLawsPosts = (await getCollection('gun-laws')) || [];
    const huntingLawsPosts = (await getCollection('hunting-laws')) || [];
    const shopPosts = (await getCollection('shop')) || [];
  
    // Combine posts from all collections
    const allPosts = [...blogPosts, ...gunLawsPosts, ...huntingLawsPosts, ...shopPosts];

```

#### blog.ts


```ts
const load = async function (): Promise<Array<Post>> {
  const blogPosts = await getCollection('blog') || [];
  const shopPosts = await getCollection('shop') || [];

  const allPosts = [...blogPosts, ...shopPosts];

  if (!allPosts.length) {
    console.error('No posts found in the collections');
    return [];
  }

  const normalizedPosts = allPosts.map(async (post) => await getNormalizedPost(post));

  const results = (await Promise.all(normalizedPosts))
    .sort((a, b) => b.publishDate.valueOf() - a.publishDate.valueOf())
    .filter((post) => !post.draft);

  return results;
};
```






## Step 2: Create a component for the collection "CollectionLatestPosts"


```

**Pull request merged**
